#!/bin/bash

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     DreamZilla Curriculum - Local Viewing Guide           ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📍 Your location: $(pwd)"
echo ""

echo "📁 CURRICULUM FILES:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1️⃣  Life Skills Manager (27KB)"
echo "   📄 src/curriculum:/life_skills_manager.py.rtf"
echo "   🎯 6-week curriculum implementation"
echo "   👉 cat src/curriculum:/life_skills_manager.py.rtf"
echo ""

echo "2️⃣  Career Development (24KB)"
echo "   📄 src/curriculum:/career_development.py.rtf"
echo "   🎯 Job discovery, AI disruption analysis, learning paths"
echo "   👉 cat src/curriculum:/career_development.py.rtf"
echo ""

echo "3️⃣  Cognitive Partner (25KB)"
echo "   📄 src/curriculum:/cognitive_partner.py.rtf"
echo "   🎯 Conversational AI interface"
echo "   👉 cat src/curriculum:/cognitive_partner.py.rtf"
echo ""

echo "4️⃣  Configuration (15KB)"
echo "   📄 config/curriculum_config.yaml.rtf"
echo "   🎯 Complete curriculum settings"
echo "   👉 cat config/curriculum_config.yaml.rtf"
echo ""

echo "5️⃣  Documentation (15KB)"
echo "   📄 docs/guides:/curriculum_guide.md.rtf"
echo "   🎯 User guide with examples"
echo "   👉 cat docs/guides:/curriculum_guide.md.rtf"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🔍 QUICK VIEW COMMANDS:"
echo ""
echo "View a file:"
echo "  cat src/curriculum:/life_skills_manager.py.rtf"
echo ""
echo "Scroll through a file:"
echo "  less src/curriculum:/life_skills_manager.py.rtf"
echo ""
echo "Search for content:"
echo "  grep 'CognitiveDiscoveryGPT' src/curriculum:/life_skills_manager.py.rtf"
echo ""
echo "Count lines:"
echo "  wc -l src/curriculum:/*.rtf"
echo ""
echo "Open in editor:"
echo "  nano src/curriculum:/life_skills_manager.py.rtf"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📖 CURRICULUM STRUCTURE:"
echo ""
echo "Week 1: Cognitive Discovery (Brain Snapshot)"
echo "Week 2: Executive Function Coach (System Fit Map)"
echo "Week 3: Reset Routine Builder (3-step regulation)"
echo "Week 4: Energy Audit & Boundaries (energy tracking)"
echo "Week 5: Self-Advocacy Trainer (advocacy scripts)"
echo "Week 6: Sustainability Planner (integration)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "✨ INTERACTIVE VIEWER:"
echo "   ./scripts/view_curriculum.sh"
echo ""

echo "📚 FULL README:"
echo "   cat CURRICULUM_README.md"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
