"""
Dyslexic AI - Complete Demo Integration

This demo shows how the prompt library integrates with an LLM
to create a complete neurodivergent-friendly AI assistant.
"""

import sys
import os
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.prompts import PromptManager


class MockLLM:
    """Mock LLM for demonstration purposes."""

    def generate(self, prompt, temperature=0.7, max_tokens=2048):
        """
        Mock LLM generation. In production, this would call
        Claude, GPT-4, or another LLM API.
        """
        # Simulate LLM response
        return f"""
Based on your request, here's a personalized response:

{self._generate_mock_response(prompt)}

---
Note: This is a mock response. In production, this would be
generated by an actual LLM like Claude or GPT-4.
"""

    def _generate_mock_response(self, prompt):
        """Generate contextual mock response."""
        if "read" in prompt.lower() and "remember" in prompt.lower():
            return """
I understand you're struggling to retain information after reading. Here's what I suggest:

1. **Before Reading**: Skim the headings and images first
2. **During Reading**: Take a 2-minute break every 15 minutes
3. **After Reading**: Summarize each section in 1-2 sentences

Memory Strategy:
- Create a mind map of the main ideas
- Use the "Feynman Technique" - explain it like you're teaching a friend
- Connect new info to things you already know

Your brain isn't broken - it just processes differently!
"""
        elif "write" in prompt.lower() or "essay" in prompt.lower():
            return """
Let's organize your writing step by step:

1. **Brain Dump**: Write all your ideas in bullet points (don't worry about order)
2. **Group**: Sort ideas into 3-4 main categories
3. **Order**: Arrange categories in a logical sequence
4. **Expand**: Turn each category into a paragraph

Writing Tip for Dyslexic Brains:
- Talk your ideas out loud first
- Use speech-to-text to capture your thoughts
- Don't edit while you're creating - separate those tasks

You have great ideas - let's get them on paper!
"""
        elif "email" in prompt.lower() or "professional" in prompt.lower():
            return """
Here's your professional email template:

Subject: [Clear, specific subject line]

Hi [Name],

I'm writing to [state your purpose in one clear sentence].

[2-3 sentences with the key information]

[What you need from them or next steps]

Thank you,
[Your name]

---

Tips for Error-Free Emails:
1. Write in a text editor first
2. Use Grammarly or similar tool
3. Read it out loud before sending
4. Have key emails reviewed by a trusted colleague

Remember: Everyone makes typos. You've got this!
"""
        else:
            return """
I hear you, and I understand this challenge. Here are some strategies tailored for dyslexic thinking:

1. Break the task into smaller pieces
2. Use visual organization (colors, mind maps, sticky notes)
3. Set up external memory systems (phone reminders, checklists)
4. Work in short focused bursts with breaks

Your dyslexic brain is creative and sees connections others miss.
Let's use those strengths to tackle this!
"""


class DyslexicAIAssistant:
    """
    Complete Dyslexic AI Assistant integrating prompt library with LLM.
    """

    def __init__(self):
        self.prompt_manager = PromptManager()
        self.llm = MockLLM()
        self.conversation_history = []

    def start(self):
        """Start the interactive assistant."""
        print("\n" + "=" * 70)
        print("🌟 DYSLEXIC AI ASSISTANT - LLM Clone for Neurodivergent Users")
        print("=" * 70)
        print("\nWelcome! I'm here to help with dyslexia-related challenges.")
        print("I have 107+ specialized prompts designed just for you.\n")

        # Get user type
        user_type = self._get_user_type()

        print(f"\n✓ Great! I'm ready to help {user_type.lower()}.\n")

        # Main interaction loop
        while True:
            print("\nWhat would you like to do?")
            print("1. Browse prompts by category")
            print("2. Search for specific help")
            print("3. Get personalized suggestions")
            print("4. See popular prompts")
            print("5. Exit")

            choice = input("\nSelect (1-5): ").strip()

            if choice == "1":
                self._browse_by_category(user_type)
            elif choice == "2":
                self._search_prompts(user_type)
            elif choice == "3":
                self._get_suggestions(user_type)
            elif choice == "4":
                self._show_popular()
            elif choice == "5":
                print("\n👋 Take care! Remember - your dyslexic brain is awesome!\n")
                break
            else:
                print("❌ Invalid choice. Please select 1-5.")

    def _get_user_type(self):
        """Get the user's type."""
        print("Who are you?")
        print("1. Student")
        print("2. Parent")
        print("3. Professional")
        print("4. Teacher")
        print("5. General")

        types = {
            "1": "Students",
            "2": "Parents",
            "3": "Professionals",
            "4": "Teachers",
            "5": "General"
        }

        choice = input("\nSelect (1-5): ").strip()
        return types.get(choice, "General")

    def _browse_by_category(self, user_type):
        """Browse prompts by category."""
        print("\n" + "=" * 70)
        print("📁 BROWSE BY CATEGORY")
        print("=" * 70)

        # Get categories relevant to user
        all_prompts = self.prompt_manager.get_prompts_by_user_type(user_type)

        # Group by category
        categories = {}
        for prompt in all_prompts:
            if prompt.category not in categories:
                categories[prompt.category] = []
            categories[prompt.category].append(prompt)

        # Display categories
        print(f"\nCategories for {user_type}:\n")
        cat_list = list(categories.keys())

        for i, category in enumerate(cat_list, 1):
            count = len(categories[category])
            print(f"{i:2d}. {category:40s} ({count} prompts)")

        # Select category
        try:
            choice = int(input("\nSelect category (or 0 to go back): "))
            if choice == 0:
                return

            selected_category = cat_list[choice - 1]
            self._show_category_prompts(categories[selected_category])

        except (ValueError, IndexError):
            print("❌ Invalid selection.")

    def _show_category_prompts(self, prompts):
        """Show prompts in a category and let user select one."""
        print(f"\n📝 Available Prompts:\n")

        for i, prompt in enumerate(prompts, 1):
            print(f"{i}. {prompt.title}")
            print(f"   When to use: {prompt.when_to_use}")
            print(f"   Type: {prompt.prompt_type}\n")

        try:
            choice = int(input("Select a prompt (or 0 to go back): "))
            if choice == 0:
                return

            selected_prompt = prompts[choice - 1]
            self._use_prompt(selected_prompt)

        except (ValueError, IndexError):
            print("❌ Invalid selection.")

    def _search_prompts(self, user_type):
        """Search for prompts."""
        print("\n" + "=" * 70)
        print("🔍 SEARCH FOR HELP")
        print("=" * 70)

        search_term = input("\nWhat do you need help with? (keywords): ").strip()

        if not search_term:
            print("❌ Please enter a search term.")
            return

        results = self.prompt_manager.search_prompts(
            user_type=user_type,
            search_term=search_term,
            limit=10
        )

        if not results:
            print(f"\n❌ No prompts found for '{search_term}'.")
            print("Try different keywords or browse by category.")
            return

        print(f"\n✓ Found {len(results)} prompts:\n")
        self._show_category_prompts(results)

    def _get_suggestions(self, user_type):
        """Get personalized suggestions."""
        print("\n" + "=" * 70)
        print("💡 PERSONALIZED SUGGESTIONS")
        print("=" * 70)

        # For demo, show popular prompts for user type
        prompts = self.prompt_manager.get_prompts_by_user_type(user_type)
        # Sort by uses (in real system, would be personalized)
        prompts.sort(key=lambda p: p.uses, reverse=True)

        print(f"\n✓ Based on what helps other {user_type.lower()}, try these:\n")
        self._show_category_prompts(prompts[:5])

    def _show_popular(self):
        """Show most popular prompts."""
        print("\n" + "=" * 70)
        print("⭐ MOST POPULAR PROMPTS")
        print("=" * 70)

        popular = self.prompt_manager.get_popular_prompts(limit=10)

        print("\n✓ These prompts have helped the most people:\n")
        self._show_category_prompts(popular)

    def _use_prompt(self, prompt):
        """Use a selected prompt with the LLM."""
        print("\n" + "=" * 70)
        print(f"🎯 USING: {prompt.title}")
        print("=" * 70)

        print(f"\nType: {prompt.prompt_type}")
        print(f"Category: {prompt.category}")
        print(f"\n{prompt.when_to_use}\n")

        # Get placeholders
        placeholders = prompt.get_placeholders()

        if not placeholders:
            # No placeholders, use as-is
            filled_prompt = prompt.full_prompt
        else:
            # Collect placeholder values
            print("I need some information to personalize this for you:\n")
            values = {}

            for placeholder in placeholders:
                value = input(f"  {placeholder}: ").strip()
                if value:
                    values[placeholder] = value

            # Fill template
            filled_prompt = prompt.fill_template(**values)

        # Show the filled prompt
        print("\n" + "-" * 70)
        print("📨 Your personalized prompt:")
        print("-" * 70)
        print(filled_prompt)
        print("-" * 70)

        # Generate response with LLM
        print("\n🤔 Thinking...")

        response = self.llm.generate(
            prompt=filled_prompt,
            temperature=0.7,
            max_tokens=2048
        )

        # Show response
        print("\n" + "=" * 70)
        print("💬 AI RESPONSE")
        print("=" * 70)
        print(response)
        print("=" * 70)

        # Track usage
        self.prompt_manager.record_usage(prompt.id)

        # Save to history
        self.conversation_history.append({
            'prompt': prompt,
            'filled_prompt': filled_prompt,
            'response': response
        })

        # Ask if helpful
        helpful = input("\n💭 Was this helpful? (y/n): ").strip().lower()
        if helpful == 'y':
            print("✓ Great! Glad I could help!")
        else:
            print("I'm sorry this wasn't helpful. Let's try something else.")

        input("\nPress Enter to continue...")


def demo_programmatic_usage():
    """
    Demo programmatic usage (without interactive UI).
    """
    print("\n" + "=" * 70)
    print("🔧 PROGRAMMATIC USAGE DEMO")
    print("=" * 70)

    # Initialize
    manager = PromptManager()
    llm = MockLLM()

    print("\n--- Example 1: Student needs reading help ---\n")

    # Get prompt
    prompt = manager.get_prompt("read_no_remember")
    print(f"Selected: {prompt.title}")

    # Fill template
    filled = prompt.fill_template(
        number="5",
        material_type="biology textbook on cellular respiration",
        paste="Cells convert glucose into ATP through a series of chemical reactions..."
    )

    print(f"\nFilled prompt preview:\n{filled[:200]}...\n")

    # Generate response
    print("Generating LLM response...\n")
    response = llm.generate(filled)
    print(f"Response:\n{response}")

    # Track usage
    manager.record_usage(prompt.id)
    print(f"\n✓ Usage recorded. This prompt has been used {prompt.uses} times.")

    print("\n" + "-" * 70)
    print("\n--- Example 2: Professional writing email ---\n")

    # Get prompt
    prompt = manager.get_prompt("crucial_email")
    print(f"Selected: {prompt.title}")

    # Fill template
    filled = prompt.fill_template(
        recipient="my department head",
        topic="requesting accommodations for dyslexia"
    )

    # Generate
    response = llm.generate(filled)
    print(f"Response:\n{response}")

    print("\n" + "=" * 70)


def show_library_stats():
    """Show library statistics."""
    print("\n" + "=" * 70)
    print("📊 DYSLEXIC AI LIBRARY STATISTICS")
    print("=" * 70)

    manager = PromptManager()
    stats = manager.get_statistics()

    print(f"\nVersion: {stats['version']}")
    print(f"Last Updated: {stats['last_updated']}")
    print(f"Total Prompts: {stats['total_prompts']}")
    print(f"Categories: {stats['categories']}")
    print(f"Total Tags: {stats['total_tags']}")
    print(f"User Types: {stats['user_types']}")

    print(f"\n--- Prompts by Type ---")
    for ptype, count in stats['prompts_by_type'].items():
        print(f"  {ptype:15s} {count:3d} prompts")

    print(f"\n--- Top 5 Categories ---")
    sorted_cats = sorted(
        stats['prompts_by_category'].items(),
        key=lambda x: x[1],
        reverse=True
    )
    for category, count in sorted_cats[:5]:
        print(f"  {category:40s} {count:3d} prompts")

    print("\n" + "=" * 70)


if __name__ == "__main__":
    import sys

    print("\n" + "=" * 70)
    print("🌟 DYSLEXIC AI - LLM Clone for Neurodivergent Users")
    print("=" * 70)
    print("\nDemo Options:")
    print("1. Interactive Assistant (full demo)")
    print("2. Programmatic Usage (code examples)")
    print("3. Library Statistics")
    print("4. Run All")

    choice = input("\nSelect (1-4): ").strip()

    if choice == "1":
        assistant = DyslexicAIAssistant()
        assistant.start()
    elif choice == "2":
        demo_programmatic_usage()
    elif choice == "3":
        show_library_stats()
    elif choice == "4":
        show_library_stats()
        demo_programmatic_usage()
        print("\n\nStarting interactive assistant...\n")
        assistant = DyslexicAIAssistant()
        assistant.start()
    else:
        print("❌ Invalid choice. Running demo_programmatic_usage()...")
        demo_programmatic_usage()

    print("\n✨ Thank you for trying Dyslexic AI!")
    print("💜 Built with love for the neurodivergent community\n")
